metricbeat.config:
  modules:
    path: /etc/metricbeat/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

# metricbeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

metricbeat.modules:
  - module: postgresql
    # metricsets: ["status"]
    # hosts: ["postgres://postgres:docker1130!#%&(@13.251.77.5:5432/starrise_test?sslmode=disable"]
    hosts: ["postgres://13.251.77.5:5432/starrise_test?sslmode=disable"]
    username: postgres
    password: docker1130!#%&(
    # sslmode: disable

# processors:
#   - add_cloud_metadata: ~


output.logstash:
  enabled: false

output.elasticsearch:
  hosts: 'http://172.31.35.30:9200'
  # username: ''
  # password: ''

setup.kibana:
  host: 'http://172.31.35.30:5601'
  # username: ''  
  # password: ''
